trigger:
- main

pool:
  name: 'Default'

steps:
- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    version: '16.x'

- script: |
    npm install
  displayName: 'NpmInstall'

- script: |
    npm run build
  displayName: 'NpmBuild'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: SwiperAngularSample
    targetPath: '$(Build.SourcesDirectory)/dist'
    publishLocation: 'pipeline'
  displayName: 'PublishNpmArtifact'

- powershell: |
    Import-Module WebAdministration
    New-Website -Name "AngularSwiperSample" -PhysicalPath "C:\azagent\_work\1\s\dist" -Port 100 -Force
  displayName: 'CreateOrUpdateWebsite'

#- task: PowerShellOnTargetMachines@3
#  inputs:
#    Machines: '172.16.0.231'
#    UserName: 'Avi'
#    UserPassword: 'Admin#123'
#    InlineScript: |
#     Import-Module WebAdministration
#      New-Website -Name "AngularSwiperSample" -PhysicalPath "C:\azagent\_work\1\s\dist\swiper-sample" -Port 100 -HostHeader "172.16.0.231:100"
#   CommunicationProtocol: 'Https'
#    NewPsSessionOptionArguments: 

#- task: IISWebAppManagementOnMachineGroup@0
#  inputs:
#    IISDeploymentType: 'IISWebsite'
#    ActionIISWebsite: 'CreateOrUpdateWebsite'
#    WebsiteName: 'AngularSwiperSample'
#    WebsitePhysicalPath: 'C:\azagent\_work\1\s\dist'
#    WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
#    AddBinding: true
#    Bindings: '100'

#- task: IISWebAppDeploymentOnMachineGroup@0
#  inputs:
#    WebSiteName: 'AngularSwiperSample'
#   Package: '$(Build.SourcesDirectory)/dist'