trigger:
- main

pool:
  name: 'Default'

steps:
- task: UseNode@1
  displayName: 'Install Node.js'
  inputs:
    version: '16.x'

- script: |
    npm install
  displayName: 'NpmInstall'

- script: |
    npm run build
  displayName: 'NpmBuild'

- task: PublishPipelineArtifact@1
  inputs:
    artifactName: SwiperAngularSample
    targetPath: '$(Build.SourcesDirectory)/dist'
    publishLocation: 'pipeline'
  displayName: 'PublishNpmArtifact'

- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    EnableIIS: true
    IISDeploymentType: 'IISWebsite'
    ActionIISWebsite: 'CreateOrUpdateWebsite'
    WebsiteName: 'AngularSwiperSample'
    WebsitePhysicalPath: 'C:\azagent\_work\1\s\dist'
    WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
    AddBinding: true
    Bindings: '120'

- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'AngularSwiperSample'
    Package: '$(Build.SourcesDirectory)/dist'